import os
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

def save_to_word(content, filename="output/Enterprise_Proposal.docx"):
    os.makedirs("output", exist_ok=True)
    doc = Document()
    
    # --- Cover Page ---
    title = doc.add_paragraph("Automated RFP Response")
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.runs[0]
    title_run.font.size = Pt(28)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(0, 51, 102) # Dark Blue
    
    subtitle = doc.add_paragraph(f"Generated by AutoRFP AI Engine\nDate: {datetime.now().strftime('%B %d, %Y')}")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_page_break()

    # --- Content Parsing ---
    paragraphs = content.split('\n')
    for p in paragraphs:
        p = p.strip()
        if not p:
            continue
            
        if p.startswith('### '):
            doc.add_heading(p.replace('### ', ''), level=3)
        elif p.startswith('## '):
            doc.add_heading(p.replace('## ', ''), level=2)
        elif p.startswith('# '):
            doc.add_heading(p.replace('# ', ''), level=1)
        elif p.startswith('**') and p.endswith('**'):
            p_obj = doc.add_paragraph()
            p_obj.add_run(p.replace('**', '')).bold = True
        elif p.startswith('- ') or p.startswith('* '):
            doc.add_paragraph(p[2:], style='List Bullet')
        else:
            doc.add_paragraph(p)
            
    doc.save(filename)
    return filename
