import os
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

def save_to_word(content, filename):
    # Filename will now be a full path to /tmp/
    doc = Document()
    title = doc.add_paragraph("Enterprise Proposal")
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.runs[0]
    run.font.size, run.font.bold, run.font.color.rgb = Pt(28), True, RGBColor(59, 130, 246)
    
    subtitle = doc.add_paragraph(f"Generated by Proposera AI Autonomous Engine\nDate: {datetime.now().strftime('%B %d, %Y')}")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_page_break()

    for p in content.split('\n'):
        p = p.strip()
        if not p: continue
        if p.startswith('### '): doc.add_heading(p.replace('### ', ''), level=3)
        elif p.startswith('## '): doc.add_heading(p.replace('## ', ''), level=2)
        elif p.startswith('# '): doc.add_heading(p.replace('# ', ''), level=1)
        elif p.startswith('**') and p.endswith('**'):
            para = doc.add_paragraph()
            para.add_run(p.replace('**', '')).bold = True
        else: doc.add_paragraph(p)
            
    doc.save(filename)
    return filename
